project:
  type: website

website:
  title: "Tomoya Uji"
  site-url: "https://tomoyauji.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
  page-footer: "© 2026 Tomoya Uji"

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    page-layout: full
    grid:
      body-width: 1100px
      margin-width: 0px
      gutter-width: 1.5rem